[package]
name = "hunch"
version = "1.0.0"
authors = []

[addresses]
hunch ="0x5f973ce279537f4b78166f0e495908ad321bae2a01aaf0d4ec6aa8e540cb631c"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]